# Generated by Django 5.2 on 2025-04-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_members_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabularyTerm', models.CharField(max_length=50)),
                ('searchRegion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
